### ISSUE TITLE
Could you release a compiled version of Build 27 for Linux?

### ISSUE THREAD

**Issue by AITYunivers** [SortaCore/bluewing-cpp-server#2]

**Comment by SortaCore** [comment]
This is a way off; while there's a Linux project, it doesn't run. I imagine there's something wrong with eventing, but haven't had time to look at it yet.
Other (paid) priorities have put this on the back burner for the foreseeable future, although I'll accept any pull requests with fixes. My current Linux test environment is Debian under WSL.

**Comment by SortaCore** [comment]
Got Linux all fixed up for [build 31](https://github.com/SortaCore/bluewing-cpp-server/commit/f09efdf87d1e15efafdb03b829a2cbe6922cd1af). Works well on Debian under WSL, and the bugs were relatively concise to fix, so I anticipate you shouldn't have any issues.

There's downloads for Linux in the [build 31 release](https://github.com/SortaCore/bluewing-cpp-server/releases/tag/unicode-build-31). Hopefully it works out of the box for you - let me know if there's still issues.

**Comment by AITYunivers** [comment]
Alrighty, thanks! I'll look into this when I have the time. For now I'll close this issue, I'll reopen it if I encounter any issues.
