### ISSUE TITLE
Some connection issues

### ISSUE THREAD

**Issue by 055110** [SortaCore/bluewing-cpp-server#3]
Hello, so I am playing IWBTB game and I set up a Bluewing server just for fun, but when I am trying to connect, I don't get the "Connected" message in the game, yet the server says I connected. Is this intended? I also tried writing in chat but I got nothing in the Bluewing server.

**Comment by SortaCore** [comment]
The standard bluewing-cpp-server will log connection, disconnection, and errors, and it'll keep re-writing a line of text at the bottom. The console window needs to be wide enough for that to work normally.

Maybe IWBTB is a custom server? Otherwise, IWBTB may not report "Connected" until it's already connected + set name, or connected + set name + joined lobby channel successfully.

**Comment by 055110** [comment]
> The standard bluewing-cpp-server will log connection, disconnection, and errors, and it'll keep re-writing a line of text at the bottom. The console window needs to be wide enough for that to work normally.
> 
> Maybe IWBTB is a custom server? Otherwise, IWBTB may not report "Connected" until it's already connected + set name, or connected + set name + joined lobby channel successfully.

Don't think it's a custom server, since it connects fine to the Dark-Wire server.

**Comment by SortaCore** [comment]
> Don't think it's a custom server, since it connects fine to the Dark-Wire server.
Then it must be the other explanation.

> Otherwise, IWBTB may not report "Connected" until it's already connected + set name, or connected + set name + joined lobby channel successfully.

There's no limitations that bluewing-cpp-server imposes, it's a stock server. Only limitation there is, is in content of client/channel names, they have to be normal letters and not all-spaces, zero width non-joiner Unicode stuff, etc.

**Comment by 055110** [comment]
I have tried running the server locally and it seems to display the "Connected" message now, IDK what caused it not to display. probably a server issue, will try to fix it myself.
